/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class com_jsbd_uart_NativeUart */

#ifndef _Included_com_jsbd_uart_NativeUart
#define _Included_com_jsbd_uart_NativeUart

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jsbd_uart_NativeUart
 * Method:    helloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jsbd_uart_NativeUart_helloWorld
  (JNIEnv *, jclass);

JNIEXPORT jobject JNICALL Java_com_jsbd_uart_NativeUart_open
  (JNIEnv *, jclass,jstring,jint,jint);

JNIEXPORT void JNICALL Java_com_jsbd_uart_NativeUart_close
  (JNIEnv *, jclass,jobject);

#ifdef __cplusplus
}
#endif
#endif
